project:
  type: book

book:
  title: "Individual Psychometrics"
  subtitle: "An Assessment Toolkit With Applications in R"
  date: "1/22/2023"
  sidebar:
    background: light
    style: docked
  author: 
    - name: "W. Joel Schneider"
      affiliation: "Temple University"
      affiliation-url: "https://education.temple.edu/about/faculty-staff/w-joel-schneider-tuh42402"
      orcid: 0000-0002-8393-5316
  chapters:
    - index.qmd
    - intro.qmd
    - variables.qmd
    - distributions.qmd
    - descriptives.qmd
    - compositescores.qmd
    - references.qmd
bibliography: [book.bib, packages.bib]
csl: "apa"
nocite: |
  @R-bookdown, @R-dplyr, @R-extrafont, @R-fBasics, @R-forcats, @R-fMultivar, @R-gganimate, @R-ggforce, @R-ggplot2, @R-IDPmisc, @R-knitr, @R-knitr, @R-purrr, @R-rmarkdown, @R-sjmisc, @R-sn, @R-stringr, @R-base, @R-tibble, @R-tidyr, @R-tidyverse, @R-tikzDevice, @R-tufte
execute:
  echo: false
  cache: true
  freeze: true
knitr: 
  opts_chunk: 
    echo: false
    tbl-cap-location: margin
    fig-cap-location: margin
    fig-width: 7
    fig-height: 5
    fig.align: center
    out-width: "100%"
    dev: "ragg_png"
citation: 
  type: book
  author: W. Joel Schneider
  issued: 2023-01-22
google-scholar: true
format:
  html:
    css: [equity.css, individualpsychometrics.css]
    html-math-method: katex
    citation-location: margin
    reference-location: margin
    mainfont: equity_text_a
    code-copy: true
    smooth-scroll: true
    toc-location: left
    toc-title: "Page Contents"
    theme: 
      - lumen
      - individualpsychometrics.scss
    grid:
      margin-width: 450px
      sidebar-width: 400px
