project:
  type: book

book:
  title: "Individual Psychometrics"
  subtitle: "An Assessment Toolkit With Applications in R"
  date: last-modified
  date-format: "[Last Updated on] MMMM DD, YYYY"
  available-date: "2020-01-01"
  sidebar:
    background: light
    style: docked
  author: 
    - name: "W. Joel Schneider"
      affiliation: "Temple University"
      affiliation-url: "https://education.temple.edu/about/faculty-staff/w-joel-schneider-tuh42402"
      orcid: 0000-0002-8393-5316
  publisher: AssessingPsyche
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        - intro.qmd
        - gettingready.qmd
        - matrix_algebra.qmd
    - part: "Variables"
      chapters: 
        - variables.qmd
        - distributions.qmd
        - descriptives.qmd
    - compositescores.qmd
    - unfinished.qmd
    - references.qmd
bibliography: [book.bib, packages.bib]
csl: "apa"
nocite: |
  @R-bookdown, @R-dplyr, @R-extrafont, @R-fBasics, @R-forcats, @R-fMultivar, @R-gganimate, @R-ggforce, @R-ggplot2, @R-IDPmisc, @R-knitr, @R-knitr, @R-purrr, @R-rmarkdown, @R-sjmisc, @R-sn, @R-stringr, @R-base, @R-tibble, @R-tidyr, @R-tidyverse, @R-tikzDevice, @R-tufte
execute:
  echo: false
  freeze: auto
  cache: true
knitr: 
  opts_chunk: 
    echo: false
    tbl-cap-location: margin
    fig-cap-location: margin
    fig-width: 7
    fig-height: 5
    fig.align: center
    out-width: "100%"
    dev: "ragg_png"
callout-icon: false
engine: knitr
filters:
  - webr
format:
  html:
    css: [equity.css, individualpsychometrics.css]
    html-math-method: katex
    self-contained: false
    citation-location: margin
    reference-location: margin
    mainfont: equity_text_a
    code-copy: true
    code-link: true
    smooth-scroll: true
    toc-location: left
    toc-title: "Page Contents"
    theme: 
      - lumen
      - individualpsychometrics.scss
    grid:
      margin-width: 450px
      sidebar-width: 400px
